# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogWithOpenCredit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenNewAccount(object):
    def setupUi(self, OpenNewCredit, banks):
        self.banks = banks
        self.amount_of_credits = 0

        OpenNewCredit.setObjectName("OpenNewAccount")
        OpenNewCredit.resize(450, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenNewCredit)
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text = QtWidgets.QLabel(OpenNewCredit)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.verticalLayout_3.addWidget(self.text)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(75, 10, 75, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BankChoice = QtWidgets.QComboBox(OpenNewCredit)
        self.BankChoice.setEditable(False)
        self.BankChoice.setMaxCount(2147483637)
        self.BankChoice.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.BankChoice.setMinimumContentsLength(0)
        self.BankChoice.setObjectName("BankChoice")
        for i in range(len(self.banks)):
            self.BankChoice.addItem("")
        self.verticalLayout_4.addWidget(self.BankChoice)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CreditSum = QtWidgets.QLineEdit(OpenNewCredit)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CreditSum.setFont(font)
        self.CreditSum.setAlignment(QtCore.Qt.AlignCenter)
        self.CreditSum.setObjectName("CreditSum")
        self.horizontalLayout_3.addWidget(self.CreditSum)
        self.Result = QtWidgets.QLineEdit(OpenNewCredit)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Result.setFont(font)
        self.Result.setAlignment(QtCore.Qt.AlignCenter)
        self.Result.setReadOnly(True)
        self.Result.setClearButtonEnabled(False)
        self.Result.setObjectName("Result")
        self.horizontalLayout_3.addWidget(self.Result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(30, 5, 30, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(OpenNewCredit)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.confirm_buuton = QtWidgets.QPushButton(OpenNewCredit)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.confirm_buuton.setFont(font)
        self.confirm_buuton.setObjectName("confirm_buuton")
        self.horizontalLayout.addWidget(self.confirm_buuton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_5)

        self.retranslateUi(OpenNewCredit)
        self.BankChoice.setCurrentIndex(0)
        self.CreditChoice.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenNewCredit)

    def retranslateUi(self, OpenNewCredit):
        _translate = QtCore.QCoreApplication.translate
        OpenNewCredit.setWindowTitle(_translate("OpenNewAccount", "BelBank"))
        self.text.setText(_translate("OpenNewAccount", "Кредит"))
        self.BankChoice.setCurrentText(_translate("OpenNewAccount", self.banks[0].name))
        for i in range(len(self.banks)):
            self.BankChoice.setItemText(i, _translate("OpenNewAccount", self.banks[i].name))
        self.CreditChoice = QtWidgets.QComboBox(OpenNewCredit)
        self.CreditChoice.setEditable(False)
        self.CreditChoice.setMaxCount(2147483637)
        self.CreditChoice.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.CreditChoice.setMinimumContentsLength(0)
        self.CreditChoice.setObjectName("CreditChoice")
        self.CreditChoice.setCurrentText(_translate("OpenNewAccount", self.banks[0].name))
        self.set_credits_choice(self.BankChoice.currentText())
        self.CreditSum.setPlaceholderText(_translate("OpenNewAccount", "Сумма кредита"))
        self.Result.setPlaceholderText(_translate("OpenNewAccount", "Итоговая выплата"))
        self.cancel_button.setText(_translate("OpenNewAccount", "Отмена"))
        self.confirm_buuton.setText(_translate("OpenNewAccount", "Послать запрос"))

    def set_credits_choice(self, bank_name):
        _translate = QtCore.QCoreApplication.translate
        for i in range(self.amount_of_credits):
            self.CreditChoice.removeItem(0)
        self.amount_of_credits = 0
        for bank in self.banks:
            if bank.name == bank_name:
                for i in range(len(bank.credits_list)):
                    self.CreditChoice.addItem("")
                    self.amount_of_credits += 1
                    self.CreditChoice.setItemText(i, _translate("OpenNewAccount", f"{bank.credits_list[i].days} дней ({bank.credits_list[i].percent}%)"))
        self.verticalLayout_4.addWidget(self.CreditChoice)
        try:
            self.Result.setText(f"{round(float(self.CreditSum.text()) * (1 + (float(self.CreditChoice.currentText().split()[2][1:-2])/100)))}")
        except:
            pass

    def set_result(self):
        try:
            self.Result.setText(f"{round(float(self.CreditSum.text()) * (1 + (float(self.CreditChoice.currentText().split()[2][1:-2])/100)))}")
        except:
            self.Result.setText("")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenNewAccount = QtWidgets.QDialog()
    ui = Ui_OpenNewAccount()
    ui.setupUi(OpenNewAccount)
    OpenNewAccount.show()
    sys.exit(app.exec_())
