# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogWithTransaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, accounts):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 238)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(50, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.my_accounts = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.my_accounts.setFont(font)
        self.my_accounts.setObjectName("my_accounts")

        self.horizontalLayout_3.addWidget(self.my_accounts)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.to_client_account = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.to_client_account.setFont(font)
        self.to_client_account.setAlignment(QtCore.Qt.AlignCenter)
        self.to_client_account.setObjectName("to_client_account")
        self.horizontalLayout.addWidget(self.to_client_account)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(150, -1, 150, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sum = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sum.setFont(font)
        self.sum.setAlignment(QtCore.Qt.AlignCenter)
        self.sum.setObjectName("sum")
        self.verticalLayout_4.addWidget(self.sum)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(25, 20, 25, -1)
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.confirm_button.setFont(font)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout_2.addWidget(self.confirm_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog, accounts)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, accounts):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.text.setText(_translate("Dialog", "Перевод"))
        for i in range(len(accounts)):
            self.my_accounts.addItem("")
            self.my_accounts.setItemText(i, _translate("Dialog", f"{accounts[i].name} | {accounts[i].money}"))
        self.to_client_account.setPlaceholderText(_translate("Dialog", "Номер счета получателя"))
        self.sum.setPlaceholderText(_translate("Dialog", "Сумма"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.confirm_button.setText(_translate("Dialog", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
