# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenuAMO.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenuAMO(object):
    def setupUi(self, MainMenuAMO):
        MainMenuAMO.setObjectName("MainMenuAMO")
        MainMenuAMO.resize(564, 391)
        self.centralwidget = QtWidgets.QWidget(MainMenuAMO)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.BelBank = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.BelBank.setFont(font)
        self.BelBank.setTextFormat(QtCore.Qt.PlainText)
        self.BelBank.setAlignment(QtCore.Qt.AlignCenter)
        self.BelBank.setObjectName("BelBank")
        self.verticalLayout_7.addWidget(self.BelBank)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BelBank_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.BelBank_2.setFont(font)
        self.BelBank_2.setTextFormat(QtCore.Qt.PlainText)
        self.BelBank_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BelBank_2.setObjectName("BelBank_2")
        self.verticalLayout.addWidget(self.BelBank_2)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.AuthorizationPart = QtWidgets.QVBoxLayout()
        self.AuthorizationPart.setContentsMargins(215, -1, 215, -1)
        self.AuthorizationPart.setSpacing(4)
        self.AuthorizationPart.setObjectName("AuthorizationPart")
        self.LoginLine = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LoginLine.setFont(font)
        self.LoginLine.setInputMask("")
        self.LoginLine.setText("")
        self.LoginLine.setAlignment(QtCore.Qt.AlignCenter)
        self.LoginLine.setObjectName("LoginLine")
        self.AuthorizationPart.addWidget(self.LoginLine)
        self.PasswordLine = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PasswordLine.setFont(font)
        self.PasswordLine.setInputMask("")
        self.PasswordLine.setText("")
        self.PasswordLine.setFrame(True)
        self.PasswordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordLine.setAlignment(QtCore.Qt.AlignCenter)
        self.PasswordLine.setClearButtonEnabled(False)
        self.PasswordLine.setObjectName("PasswordLine")
        self.AuthorizationPart.addWidget(self.PasswordLine)
        self.EnterButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.EnterButton.setFont(font)
        self.EnterButton.setDefault(True)
        self.EnterButton.setFlat(False)
        self.EnterButton.setObjectName("EnterButton")
        self.AuthorizationPart.addWidget(self.EnterButton)
        self.verticalLayout_7.addLayout(self.AuthorizationPart)
        MainMenuAMO.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenuAMO)
        QtCore.QMetaObject.connectSlotsByName(MainMenuAMO)

    def retranslateUi(self, MainMenuAMO):
        _translate = QtCore.QCoreApplication.translate
        MainMenuAMO.setWindowTitle(_translate("MainMenuAMO", "BelBank"))
        self.BelBank.setText(_translate("MainMenuAMO", "BelBank"))
        self.BelBank_2.setText(_translate("MainMenuAMO", "Вы авторизируетесь как сотрудник банковской системы"))
        self.LoginLine.setPlaceholderText(_translate("MainMenuAMO", "Логин"))
        self.PasswordLine.setPlaceholderText(_translate("MainMenuAMO", "Пароль"))
        self.EnterButton.setText(_translate("MainMenuAMO", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenuAMO = QtWidgets.QMainWindow()
    ui = Ui_MainMenuAMO()
    ui.setupUi(MainMenuAMO)
    MainMenuAMO.show()
    sys.exit(app.exec_())
